iSeries:
  Sia:
    settings:
      appName: 'neos-sia'
      enpoint: 'siasky.net'
      endpointSendPath: '/skynet/skyfile' # no ending "/"
      hnsDomain: 'hns.siasky.net'
      urlHeadersAccept: 'application/json'
      urlHeadersUserAgent: 'Sia-Agent-2'
      apiKey: '' # apiKey for auth password
      customCookie: '' # custom cookie
      apiClientOptions:
      profiles:
        # Default credentials and client options
        # Override these in your settings with real values
        default:
          credentials:
            username: '' # Authentication username to use.
            password: '' #  Authentication password to use.
            userAgent: 'Sia-Agent-2' # Default UserAgent.