iSeries:
  Sia:
    settings:
      appName: 'neos-sia'
      enpoint: 'siasky.net'
      endpointSendPath: '/skynet/skyfile' # no ending "/"
      hnsDomain: 'hns.siasky.net'
      urlHeadersAccept: 'application/json'
      urlHeadersUserAgent: 'Sia-Agent-2'
      apiKey: '' # apiKey for auth password
      customCookie: '' # custom cookie
      apiClientOptions: